"""Initial migration: Create user management system

Revision ID: 90d050faabb1
Revises: 
Create Date: 2025-11-14 01:53:50.949819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d050faabb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='사용자 고유 ID (UUID)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='비밀번호 해시 (소셜 로그인 시 NULL)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='사용자 이름'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='계정 활성화 상태'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True, comment='이메일 인증 완료 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='계정 생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='최종 업데이트 시간'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_consents',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='사용자 ID (FK)'),
    sa.Column('privacy_policy', sa.Boolean(), nullable=True, comment='개인정보 처리방침 동의 (필수)'),
    sa.Column('terms_of_service', sa.Boolean(), nullable=True, comment='서비스 이용약관 동의 (필수)'),
    sa.Column('push_notification', sa.Boolean(), nullable=True, comment='푸시 알림 수신 동의'),
    sa.Column('marketing_notification', sa.Boolean(), nullable=True, comment='마케팅 알림 수신 동의'),
    sa.Column('data_analytics', sa.Boolean(), nullable=True, comment='데이터 분석 활용 동의'),
    sa.Column('personalized_ads', sa.Boolean(), nullable=True, comment='개인화 광고 활용 동의'),
    sa.Column('consent_version', sa.String(length=50), nullable=True, comment='동의한 약관 버전'),
    sa.Column('consent_ip', sa.String(length=45), nullable=True, comment='동의 시점 IP 주소'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='최초 동의 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='동의 변경 시간'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='사용자 ID (FK)'),
    sa.Column('age', sa.Integer(), nullable=True, comment='나이 (필수 온보딩 정보)'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='거주 지역 (필수 온보딩 정보)'),
    sa.Column('job_category', sa.String(length=50), nullable=True, comment='직업 카테고리 (학생, 직장인, 무직, 기타)'),
    sa.Column('employment_status', sa.String(length=50), nullable=True, comment='고용 상태 (재직, 구직, 자영업, 기타)'),
    sa.Column('income_range', sa.String(length=50), nullable=True, comment='소득 구간 (2000만원 이하, 2000-4000만원, 등)'),
    sa.Column('education_level', sa.String(length=50), nullable=True, comment='학력 (고졸, 대졸, 대학원 등)'),
    sa.Column('goals', sa.JSON(), nullable=True, comment='사용자 목표 (적금, 투자, 주택 등) JSON 배열'),
    sa.Column('interests', sa.JSON(), nullable=True, comment='관심 정책 카테고리 JSON 배열'),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True, comment='온보딩 완료 여부'),
    sa.Column('profile_completion_rate', sa.Integer(), nullable=True, comment='프로필 완성도 퍼센트 (0-100)'),
    sa.Column('preferred_language', sa.String(length=10), nullable=True, comment='선호 언어 (ko, en)'),
    sa.Column('ai_personality', sa.String(length=50), nullable=True, comment='AI 성격 설정 (친근한, 전문적인, 간결한)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_social_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='소셜 계정 연동 ID'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='사용자 ID (FK)'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='소셜 제공자 (google, kakao, naver)'),
    sa.Column('provider_id', sa.String(length=255), nullable=False, comment='제공자별 사용자 고유 ID'),
    sa.Column('provider_email', sa.String(length=255), nullable=True, comment='제공자에서 제공한 이메일'),
    sa.Column('provider_data', sa.JSON(), nullable=True, comment='제공자 프로필 데이터 (이름, 사진 등)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='연동 활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='연동 생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='연동 정보 업데이트 시간'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 소셜 계정 연동 테이블'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_social_accounts')
    op.drop_table('user_profiles')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
